apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sso-postgresql
  namespace: sso
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: my-standard-csi